# Generated by Django 6.0.6 on 2026-07-04 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_attendances', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='church.service')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='visitors.visitor')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-check_in_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('visitor', 'service'), name='unique_visitor_per_service')],
            },
        ),
    ]
