# Generated by Django 6.0.6 on 2026-07-17 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('visitors', '0002_visitor_is_qr_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Duplicate', 'Duplicate'), ('Invalid', 'Invalid'), ('Revoked', 'Revoked')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='visitors.visitor')),
            ],
            options={
                'db_table': 'scan_logs',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
