# Generated by Django 6.0.6 on 2026-06-29 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('qr_code_hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('physical_address', models.TextField(blank=True)),
                ('country', models.CharField(default='Kenya', max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('visitor_type', models.CharField(choices=[('First Time', 'First Time'), ('Returning', 'Returning')], default='First Time', max_length=20)),
                ('invited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_inviter', models.CharField(blank=True, max_length=255, null=True)),
                ('purpose_of_visit', models.TextField(blank=True)),
                ('seat_number', models.CharField(blank=True, max_length=20, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=255, null=True)),
                ('children', models.TextField(blank=True, help_text='Names and ages of children')),
                ('special_needs', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('prayer_request', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('consent_sms', models.BooleanField(default=False)),
                ('consent_whatsapp', models.BooleanField(default=False)),
                ('consent_email', models.BooleanField(default=False)),
                ('gps_location', models.CharField(blank=True, help_text="Stored as 'lat, lng' string", max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.branch')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visitors', to=settings.AUTH_USER_MODEL)),
                ('service_attended', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.service')),
            ],
            options={
                'db_table': 'visitors',
                'ordering': ['-created_at'],
            },
        ),
    ]
