# Generated by Django 6.0.6 on 2026-07-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='is_qr_active',
            field=models.BooleanField(default=True, help_text='Set to False to revoke a compromised QR code'),
        ),
    ]
