# Generated by Django 6.0.6 on 2026-07-04 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Called', 'Called'), ('Visited', 'Visited'), ('Prayed With', 'Prayed With'), ('Interested', 'Interested'), ('Joined Church', 'Joined Church'), ('Baptized', 'Baptized'), ('Member', 'Member'), ('Inactive', 'Inactive'), ('No Response', 'No Response'), ('Lost Contact', 'Lost Contact')], default='Pending', max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='visitors.visitor')),
            ],
            options={
                'db_table': 'followups',
                'ordering': ['due_date'],
            },
        ),
    ]
